on: 
  push:
    branches:
      - '*'

jobs:
  unit-test:
    name: "unit-test"
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v3
      - name: run test
        run: chmod 777 launch_cmake.sh && ./launch_cmake.sh

      
